CREATE TABLE kondisiruangan(
   ID int NOT NULL AUTO_INCREMENT PRIMARY KEY
  ,Nama_Kecamatan VARCHAR(16) NOT NULL 
  ,Nama_Sekolah   VARCHAR(50) NOT NULL
  ,Baik           INTEGER  NOT NULL
  ,Rusak_Ringan   INTEGER  NOT NULL
  ,Rusak_Sedang   INTEGER  NOT NULL
  ,Rusak_Berat    INTEGER  NOT NULL
  ,Jumlah_Ruangan INTEGER  NOT NULL
);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Sumur Bandung','SDN 001 MERDEKA KOTA BANDUNG',0,8,0,0,8);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Andir','SDN 002 KARANGMULYA KOTA BANDUNG',0,6,0,2,8);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Astanaanyar','SDN 003 PAGARSIH KOTA BANDUNG',0,0,0,7,7);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Arcamanik','SDN 004 CISARANTEN KULON KOTA BANDUNG',0,10,0,0,10);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Babakan Ciparay','SDN 005 BABAKAN CIPARAY KOTA BANDUNG',5,5,0,0,10);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Buahbatu','SDN 006 BUAHBATU KOTA BANDUNG',0,18,0,0,18);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Coblong','SDN 007 CIPAGANTI KOTA BANDUNG',0,8,0,0,8);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Regol','SDN 008 MOHAMAD TOHA KOTA BANDUNG',0,13,1,0,14);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Mandalajati','SDN 009 CIKADUT KOTA BANDUNG',0,8,1,0,9);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Cidadap','SDN 010 CIDADAP KOTA BANDUNG',0,2,1,3,6);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Bandung Kulon','SDN 011 CIBUNTU KOTA BANDUNG',0,0,9,1,10);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Babakan Ciparay','SDN 012 BABAKAN CIPARAY KOTA BANDUNG',12,0,0,0,12);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Cicendo','SDN 013 PASIRKALIKI KOTA BANDUNG',0,3,7,3,13);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Bandung Kulon','SDN 014 CIGONDEWAH KOTA BANDUNG',0,4,5,1,10);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Cicendo','SDN 015 KRESNA KOTA BANDUNG',20,0,0,0,20);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Cicendo','SDN 016 DR. CIPTO PAJAJARAN KOTA BANDUNG',0,20,0,0,20);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Kiaracondong','SDN 017 SEKEJATI KOTA BANDUNG',1,4,0,0,5);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Sukajadi','SDN 018 SUKAGALIH KOTA BANDUNG',0,9,0,0,9);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Astanaanyar','SDN 019 PABAKI KOTA BANDUNG',48,0,0,0,48);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Regol','SDN 020 LENGKONG BESAR KOTA BANDUNG',0,20,0,0,20);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Ujungberung','SDN 021 CIPOREAT KOTA BANDUNG',8,4,0,0,12);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Cibeunying Kidul','SDN 022 CICADAS KOTA BANDUNG',7,5,1,0,13);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Astanaanyar','SDN 023 PAJAGALAN KOTA BANDUNG',0,24,0,0,24);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Coblong','SDN 024 COBLONG KOTA BANDUNG',23,1,0,0,24);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Cibeunying Kaler','SDN 025 CIKUTRA KOTA BANDUNG',0,17,3,0,20);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Bojong Loa Kidul','SDN 026 BOJONGLOA KOTA BANDUNG',0,15,0,1,16);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Cibeunying Kidul','SDN 027 CICADAS KOTA BANDUNG',0,21,0,0,21);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Batununggal','SDN 028 GUMURUH KOTA BANDUNG',0,14,0,0,14);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Cibiru','SDN 029 CILENGKRANG KOTA BANDUNG',0,4,4,6,14);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Cidadap','SDN 030 CIRATEUN KOTA BANDUNG',0,12,0,0,12);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Coblong','SDN 031 PELESIRAN KOTA BANDUNG',10,0,0,0,10);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Coblong','SDN 032 TILIL KOTA BANDUNG',13,1,0,0,14);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Regol','SDN 033 ASMI KOTA BANDUNG',0,24,5,1,30);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Sumur Bandung','SDN 034 PATRAKOMALA KOTA BANDUNG',0,11,1,1,13);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Sumur Bandung','SDN 035 SOKA KOTA BANDUNG',33,4,0,0,37);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Ujungberung','SDN 036 UJUNGBERUNG KOTA BANDUNG',29,0,0,0,29);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Bandung Wetan','SDN 037 SABANG KOTA BANDUNG',34,0,0,0,34);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Kiaracondong','SDN 038 KIARACONDONG KOTA BANDUNG',4,2,0,0,6);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Astanaanyar','SDN 039 TEGALEGA KOTA BANDUNG',0,0,0,11,11);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Bandung Kidul','SDN 040 PASAWAHAN KOTA BANDUNG',12,0,0,0,12);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Bandung Kulon','SDN 041 CIBUNTU WARUNG MUNCANG KOTA BANDUNG',10,0,0,0,10);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Batununggal','SDN 042 GAMBIR KOTA BANDUNG',11,3,0,0,14);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Cibeunying Kidul','SDN 043 CIMUNCANG KOTA BANDUNG',24,0,0,0,24);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Cibeunying Kidul','SDN 044 CICADAS AWIGOMBONG KOTA BANDUNG',0,20,0,0,20);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Cicendo','SDN 045 PASIRKALIKI KOTA BANDUNG',2,4,0,0,6);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Mandalajati','SDN 046 SINDANGLAYA KOTA BANDUNG',0,5,3,0,8);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Regol','SDN 047 BALONGGEDE KOTA BANDUNG',0,12,0,1,13);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Sukajadi','SDN 048 SIRNAMANAH KOTA BANDUNG',7,8,0,0,15);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Andir','SDN 049 DURMAN KOTA BANDUNG',8,0,0,0,8);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Cibiru','SDN 050 CIBIRU KOTA BANDUNG',0,19,0,0,19);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Cicendo','SDN 051 PASIRKALIKI KOTA BANDUNG',10,0,0,0,10);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Cinambo','SDN 052 CISARANTEN WETAN GEDEBAGE KOTA BANDUNG',0,16,0,0,16);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Coblong','SDN 053 CISITU KOTA BANDUNG',4,20,5,0,29);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Coblong','SDN 054 TIKUKUR KOTA BANDUNG',15,0,0,0,15);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Mandalajati','SDN 055 JATIHANDAP KOTA BANDUNG',0,0,8,0,8);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Andir','SDN 056 GARUDA DADALI KOTA BANDUNG',0,17,3,0,20);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Arcamanik','SDN 057 BINAHARAPAN KOTA BANDUNG',14,1,0,0,15);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Babakan Ciparay','SDN 058 BABAKAN CIPARAY KOTA BANDUNG',0,9,2,1,12);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Babakan Ciparay','SDN 059 CIRANGRANG KOTA BANDUNG',0,15,4,2,21);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Babakan Ciparay','SDN 060 RAYA BARAT KOTA BANDUNG',30,0,0,0,30);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Bandung Kulon','SDN 061 CIJERAH KOTA BANDUNG',0,4,0,3,7);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Bandung Wetan','SDN 062 CIUJUNG KOTA BANDUNG',0,8,1,7,16);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Batununggal','SDN 063 KEBON GEDANG KOTA BANDUNG',26,0,0,0,26);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Cibeunying Kidul','SDN 064 PADASUKA KOTA BANDUNG',7,13,0,0,20);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Coblong','SDN 065 CIHAMPELAS KOTA BANDUNG',0,15,0,0,15);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Lengkong','SDN 066 HALIMUN KOTA BANDUNG',0,26,0,0,26);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Lengkong','SDN 067 NILEM KOTA BANDUNG',10,7,0,0,17);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Mandalajati','SDN 068 SINDANGLAYA KOTA BANDUNG',0,11,0,0,11);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Rancasari','SDN 069 CIPAMOKOLAN DERWATI KOTA BANDUNG',0,13,0,6,19);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Regol','SDN 070 PASIRLUYU KOTA BANDUNG',0,7,0,0,7);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Sukajadi','SDN 071 SUKAGALIH KOTA BANDUNG',2,9,0,7,18);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Sukajadi','SDN 072 SUKASARI KOTA BANDUNG',0,7,0,0,7);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Astanaanyar','SDN 073 PAJAGALAN KOTA BANDUNG',0,0,12,0,12);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Cicendo','SDN 074 AYUDIA KOTA BANDUNG',0,6,3,0,9);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Cicendo','SDN 075 JATAYU KOTA BANDUNG',0,14,0,0,14);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Sukajadi','SDN 076 SUKAJADI KOTA BANDUNG',0,7,0,0,7);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Sukajadi','SDN 077 SEJAHTERA KOTA BANDUNG',11,7,0,0,18);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Antapani','SDN 078 SINDANGSARI ANTAPANI KOTA BANDUNG',0,8,1,0,9);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Astanaanyar','SDN 079 KOPO PAJAGALAN KOTA BANDUNG',2,19,0,0,21);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Bandung Kulon','SDN 080 BOJONG INDAH CIBUNTU KOTA BANDUNG',5,5,0,0,10);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Batununggal','SDN 081 KEBON GEDANG KRIDAWINAYA KOTA BANDUNG',1,17,0,0,18);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Cibeunying Kaler','SDN 082 MUARARAJEUN KOTA BANDUNG',0,13,0,0,13);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Kiaracondong','SDN 083 BABAKAN SURABAYA KOTA BANDUNG',0,0,1,8,9);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Mandalajati','SDN 084 CIKADUT KOTA BANDUNG',0,5,0,0,5);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Cidadap','SDN 085 CIUMBULEUIT KOTA BANDUNG',1,7,2,0,10);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Gedebage','SDN 086 CIMINCRANG KOTA BANDUNG',2,4,0,0,6);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Rancasari','SDN 087 RANCABOLANG KOTA BANDUNG',0,13,0,0,13);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Sumur Bandung','SDN 088 EMBONG KOTA BANDUNG',0,10,2,0,12);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Babakan Ciparay','SDN 089 BABAKAN CIPARAY KOTA BANDUNG',4,6,0,0,10);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Cibiru','SDN 090 CIBIRU KOTA BANDUNG',0,16,0,0,16);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Andir','SDN 091 CIBEUREUM KOTA BANDUNG',41,5,0,0,46);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Astanaanyar','SDN 092 CIBADAK ANDIR KOTA BANDUNG',2,13,0,0,15);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Bandung Kulon','SDN 093 TUNAS HARAPAN CIJERAH KOTA BANDUNG',0,7,10,0,17);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Bandung Kidul','SDN 094 PARAKANWAAS KOTA BANDUNG',4,2,0,0,6);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Buahbatu','SDN 095 BABAKANJATI KOTA BANDUNG',1,7,0,0,8);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Sukajadi','SDN 096 SARIJADI SELATAN KOTA BANDUNG',0,12,0,0,12);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Sukasari','SDN 097 CIRATEUN KULON KOTA BANDUNG',0,6,0,0,6);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Andir','SDN 098 CIROYOM KOTA BANDUNG',0,5,0,0,5);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Bojong Loa Kaler','SDN 099 BABAKAN TAROGONG KOTA BANDUNG',14,1,0,0,15);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Sukasari','SDN 100 CIPEDES KOTA BANDUNG',0,4,0,1,5);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Arcamanik','SDN 101 SUKAKARYA KOTA BANDUNG',0,6,5,1,12);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Cibiru','SDN 102 CIKUDAYASA KOTA BANDUNG',0,7,0,0,7);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Coblong','SDN 103 COBLONG KOTA BANDUNG',6,0,0,0,6);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Coblong','SDN 104 LANGENSARI SENANGGALIH KOTA BANDUNG',15,3,0,0,18);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Panyileukan','SDN 105 SUKARELA KOTA BANDUNG',0,9,0,0,9);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Ujungberung','SDN 106 AJITUNGGAL CIJAMBE KOTA BANDUNG',0,4,3,5,12);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Ujungberung','SDN 107 PALEDANG KOTA BANDUNG',7,0,0,0,7);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Cidadap','SDN 108 CIUMBULEUIT KOTA BANDUNG',0,6,0,0,6);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Batununggal','SDN 109 CENTEH KOTA BANDUNG',4,12,1,1,18);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Cicendo','SDN 110 PASIRKALIKI KOMARABUDI KOTA BANDUNG',2,9,0,0,11);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Kiaracondong','SDN 111 PINDAD KOTA BANDUNG',0,7,0,0,7);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Regol','SDN 112 PAMOYANAN KOTA BANDUNG',0,13,0,0,13);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Sumur Bandung','SDN 113 BANJARSARI KOTA BANDUNG',35,3,0,0,38);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Cibeunying Kidul','SDN 114 BOJONGKONENG CIBEUNYING KOTA BANDUNG',0,10,0,0,10);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Lengkong','SDN 115 TURANGGA KOTA BANDUNG',0,7,0,0,7);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Kiaracondong','SDN 116 CICAHEUM KOTA BANDUNG',0,6,0,0,6);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Bandung Kidul','SDN 117 BATUNUNGGAL KOTA BANDUNG',0,0,6,0,6);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Bojong Loa Kaler','SDN 118 TANJUNG KOTA BANDUNG',0,1,3,4,8);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Lengkong','SDN 119 CIJAGRA KOTA BANDUNG',5,6,0,0,11);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Regol','SDN 120 KOTABARU KOTA BANDUNG',0,0,2,4,6);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Bandung Kulon','SDN 121 CARINGIN HOLIS KOTA BANDUNG',3,7,0,0,10);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Rancasari','SDN 122 CIJAWURA KOTA BANDUNG',3,10,0,0,13);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Regol','SDN 123 BABAKAN PRIANGAN KOTA BANDUNG',3,4,0,0,7);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Cibiru','SDN 124 HANURA KOTA BANDUNG',3,3,2,0,8);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Cibiru','SDN 125 TARUNA KARYA KOTA BANDUNG',0,4,0,2,6);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Babakan Ciparay','SDN 126 BABAKAN KOTA BANDUNG',1,6,0,0,7);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Coblong','SDN 127 SEKELOA KOTA BANDUNG',0,6,0,0,6);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Coblong','SDN 128 HAURPANCUH KOTA BANDUNG',0,4,9,7,20);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Buahbatu','SDN 129 RANCASAWO MARGASARI KOTA BANDUNG',0,28,0,1,29);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Bandung Kidul','SDN 130 SEKELIMUS BATUNUNGGAL KOTA BANDUNG',10,0,0,9,19);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Buahbatu','SDN 131 CIJAWURA KOTA BANDUNG',0,6,2,1,9);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Cibeunying Kaler','SDN 132 CIHAURGEULIS KOTA BANDUNG',13,0,0,0,13);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Cibeunying Kidul','SDN 133 JALAN ANYAR KOTA BANDUNG',5,1,0,0,6);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Cidadap','SDN 134 PANORAMA KOTA BANDUNG',4,14,0,0,18);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Lengkong','SDN 135 TURANGGA KOTA BANDUNG',0,6,4,0,10);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Sukajadi','SDN 136 SUKAWARNA KOTA BANDUNG',0,30,0,0,30);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Sukasari','SDN 137 CIJEROKASO KOTA BANDUNG',0,11,0,1,12);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Sukasari','SDN 138 GEGERKALONG GIRANG KOTA BANDUNG',0,15,0,0,15);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Sukasari','SDN 139 SUKARASA KOTA BANDUNG',0,5,0,0,5);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Arcamanik','SDN 140 ARCAMANIK KOTA BANDUNG',0,7,0,0,7);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Arcamanik','SDN 141 LOKAJAYA KOTA BANDUNG',3,5,5,0,13);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Astanaanyar','SDN 142 DWIKORA KOTA BANDUNG',7,0,0,0,7);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Astanaanyar','SDN 143 KOPO KOTA BANDUNG',0,5,0,0,5);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Babakan Ciparay','SDN 144 SITUGUNTING KOTA BANDUNG',4,1,0,0,5);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Batununggal','SDN 145 BINONG JATI KOTA BANDUNG',0,7,4,1,12);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Batununggal','SDN 146 GUMURUH KOTA BANDUNG',2,10,0,0,12);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Bojong Loa Kaler','SDN 147 CITARIP BARAT KOTA BANDUNG',9,2,0,0,11);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Bojong Loa Kidul','SDN 148 CIBADUYUT KOTA BANDUNG',4,3,0,7,14);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Cibeunying Kaler','SDN 149 CIGADUNG KOTA BANDUNG',8,6,0,0,14);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Cibeunying Kidul','SDN 150 GATOT SUBROTO KOTA BANDUNG',0,12,0,0,12);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Cibeunying Kidul','SDN 151 SUKASENANG KOTA BANDUNG',0,11,1,2,14);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Cibiru','SDN 152 CIGAGAK KOTA BANDUNG',0,7,0,0,7);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Cibiru','SDN 153 TARUNA KARYA KOTA BANDUNG',0,0,8,0,8);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Cicendo','SDN 154 CITEPUS KOTA BANDUNG',0,16,0,0,16);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Cicendo','SDN 155 GUNUNG RAHAYU KOTA BANDUNG',0,14,0,0,14);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Cicendo','SDN 156 PASIRKALIKI KOTA BANDUNG',0,12,0,0,12);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Cicendo','SDN 157 SUKARAJA KOTA BANDUNG',0,6,0,0,6);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Kiaracondong','SDN 158 BABAKAN SARI BABAKAN SURABAYA KOTA BANDUNG',0,6,6,2,14);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Kiaracondong','SDN 159 SEKEJATI KOTA BANDUNG',3,4,0,2,9);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Kiaracondong','SDN 160 SUKALAKSANA KOTA BANDUNG',0,10,0,4,14);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Kiaracondong','SDN 161 SUKAPURA KOTA BANDUNG',0,14,0,0,14);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Kiaracondong','SDN 162 WARUNGJAMBU KIARACONDONG KOTA BANDUNG',0,12,1,0,13);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Lengkong','SDN 163 BUAHBATU BARU KOTA BANDUNG',9,1,0,0,10);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Lengkong','SDN 164 KARANGPAWULANG KOTA BANDUNG',0,39,0,0,39);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Mandalajati','SDN 165 JATIHANDAP KOTA BANDUNG',0,1,2,0,3);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Regol','SDN 166 CIATEUL KOTA BANDUNG',8,0,0,0,8);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Regol','SDN 167 MENGGER GIRANG KOTA BANDUNG',0,7,1,0,8);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Cibiru','SDN 168 CIPADUNG KOTA BANDUNG',0,7,3,2,12);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Cibiru','SDN 169 PELITA KOTA BANDUNG',0,6,0,4,10);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Cicendo','SDN 170 DIAN KOTA BANDUNG',0,12,0,0,12);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Cicendo','SDN 171 LANUMA HUSEIN KOTA BANDUNG',0,0,4,3,7);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Cinambo','SDN 172 ANDIR KIDUL KOTA BANDUNG',0,14,0,0,14);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Coblong','SDN 173 NEGLASARI KOTA BANDUNG',7,7,0,0,14);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Mandalajati','SDN 174 PASIR IMPUN KOTA BANDUNG',0,0,8,0,8);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Mandalajati','SDN 175 TANJAKAN KOTA BANDUNG',3,2,0,0,5);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Sukasari','SDN 176 CILANDAK KOTA BANDUNG',0,7,0,0,7);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Sukasari','SDN 177 CIPEDES KOTA BANDUNG',2,10,2,1,15);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Sukasari','SDN 178 GEGERKALONG KPAD KOTA BANDUNG',0,12,1,3,16);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Sukasari','SDN 179 SARIJADI KOTA BANDUNG',3,9,1,2,15);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Arcamanik','SDN 180 PRAKARSA NUGRAHA KOTA BANDUNG',0,6,2,3,11);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Arcamanik','SDN 181 SUKAMISKIN KOTA BANDUNG',14,0,0,0,14);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Bandung Kulon','SDN 182 PERUMNAS CIJERAH KOTA BANDUNG',0,12,1,1,14);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Bandung Kulon','SDN 183 SAYURAN KOTA BANDUNG',0,5,0,0,5);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Buahbatu','SDN 184 BUAHBATU KOTA BANDUNG',0,7,0,0,7);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Cibeunying Kaler','SDN 185 CIHAURGEULIS KOTA BANDUNG',6,0,0,0,6);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Cibiru','SDN 186 CIPADUNG KOTA BANDUNG',0,6,0,0,6);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Cicendo','SDN 187 LANUMA HUSEIN KOTA BANDUNG',1,9,2,0,12);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Cidadap','SDN 188 BANDUNG BARU KOTA BANDUNG',0,10,2,1,13);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Coblong','SDN 189 NEGLASARI KOTA BANDUNG',16,0,0,0,16);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Gedebage','SDN 190 CISARANTEN KIDUL KOTA BANDUNG',0,40,0,0,40);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Kiaracondong','SDN 191 BABAKAN SURABAYA KOTA BANDUNG',10,8,0,0,18);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Regol','SDN 192 CIBURUY KOTA BANDUNG',0,2,4,1,7);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Sukajadi','SDN 193 CARINGIN KOTA BANDUNG',0,17,0,1,18);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Sukajadi','SDN 194 SUKAJADI KOTA BANDUNG',0,2,1,4,7);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Sukasari','SDN 195 ISOLA KOTA BANDUNG',0,9,0,0,9);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Sukasari','SDN 196 SUKARASA KOTA BANDUNG',0,19,0,0,19);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Andir','SDN 197 KARANG TARUNA KARANGSARI KOTA BANDUNG',0,1,6,18,25);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Arcamanik','SDN 198 MEKARJAYA KOTA BANDUNG',8,0,1,0,9);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Bandung Kulon','SDN 199 SAYURAN KOTA BANDUNG',0,12,0,0,12);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Bojong Loa Kidul','SDN 200 LEUWIPANJANG KOTA BANDUNG',0,12,0,0,12);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Cibeunying Kaler','SDN 201 SUKALUYU KOTA BANDUNG',0,15,1,0,16);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Lengkong','SDN 202 SURYALAYA KOTA BANDUNG',0,2,5,1,8);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Batununggal','SDN 203 KACAPIRING KOTA BANDUNG',0,15,0,0,15);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Cidadap','SDN 204 CIDADAP KOTA BANDUNG',0,8,0,0,8);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Coblong','SDN 205 NEGLASARI KOTA BANDUNG',0,9,1,0,10);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Lengkong','SDN 206 PUTRACO INDAH KOTA BANDUNG',0,0,6,0,6);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Sukajadi','SDN 207 CIBOGO KOTA BANDUNG',1,7,0,0,8);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Sukajadi','SDN 208 LUGINASARI SUKAGALIH KOTA BANDUNG',0,8,3,1,12);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Antapani','SDN 209 ANTAPANI KOTA BANDUNG',0,5,3,1,9);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Kiaracondong','SDN 210 BABAKAN SINYAR KOTA BANDUNG',0,12,0,0,12);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Regol','SDN 211 BABAKAN PRIANGAN KOTA BANDUNG',1,6,4,0,11);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Sukasari','SDN 212 HARAPAN KOTA BANDUNG',0,12,0,0,12);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Babakan Ciparay','SDN 213 BABAKAN CIPARAY KOTA BANDUNG',0,6,0,0,6);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Bandung Kulon','SDN 214 PERUMNAS CIJERAH KOTA BANDUNG',0,6,0,0,6);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Gedebage','SDN 215 RANCASAGATAN KOTA BANDUNG',5,1,0,0,6);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Gedebage','SDN 216 SONDARIAH KOTA BANDUNG',0,4,0,1,5);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Sukasari','SDN 217 SARIJADI KOTA BANDUNG',0,5,0,0,5);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Sukasari','SDN 218 SARIJADI KOTA BANDUNG',7,3,2,0,12);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Batununggal','SDN 219 BABAKANJATI KOTA BANDUNG',3,4,2,0,9);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Batununggal','SDN 220 GUMURUH KOTA BANDUNG',0,6,0,0,6);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Kiaracondong','SDN 221 BABAKAN SENTRAL KOTA BANDUNG',9,1,0,0,10);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Rancasari','SDN 222 PASIRPOGOR KOTA BANDUNG',0,9,7,0,16);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Regol','SDN 223 BHAKTI WINAYA KOTA BANDUNG',0,17,0,0,17);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Ujungberung','SDN 224 CIJAMBE KOTA BANDUNG',0,7,0,0,7);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Ujungberung','SDN 225 MEKARGALIH KOTA BANDUNG',0,4,0,3,7);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Arcamanik','SDN 226 ARCAMANIK ENDAH KOTA BANDUNG',0,11,0,0,11);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Babakan Ciparay','SDN 227 MARGAHAYU UTARA KOTA BANDUNG',0,10,0,1,11);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Bojong Loa Kidul','SDN 228 CANGKUANG KOTA BANDUNG',2,2,0,5,9);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Bojong Loa Kidul','SDN 229 CIBADUYUT KOTA BANDUNG',4,1,2,0,7);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Buahbatu','SDN 230 MARGAHAYU RAYA KOTA BANDUNG',1,7,0,0,8);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Mandalajati','SDN 231 SUKAASIH KOTA BANDUNG',0,0,0,0,0);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Bandung Kulon','SDN 232 BLOK SAWAH KOTA BANDUNG',0,6,0,0,6);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Bojong Loa Kidul','SDN 233 CIBADUYUT KOTA BANDUNG',0,6,0,0,6);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Cibeunying Kidul','SDN 234 SALUYU KOTA BANDUNG',8,0,0,0,8);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Lengkong','SDN 235 LENGKONG KECIL KOTA BANDUNG',4,1,4,0,9);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Babakan Ciparay','SDN 236 BABAKAN CIPARAY KOTA BANDUNG',0,5,0,0,5);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Babakan Ciparay','SDN 237 KOPO ELOK KOTA BANDUNG',0,5,0,0,5);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Bandung Kulon','SDN 238 CIGONDEWAH KOTA BANDUNG',0,4,1,0,5);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Bandung Kulon','SDN 239 CIGONDEWAH KOTA BANDUNG',0,7,1,0,8);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Bandung Kulon','SDN 240 CIJERAH INDAH KOTA BANDUNG',0,11,0,0,11);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Bojong Loa Kidul','SDN 241 LEUWIANYAR KOTA BANDUNG',0,5,1,0,6);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Buahbatu','SDN 242 MARGASARI KOTA BANDUNG',0,3,0,3,6);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Mandalajati','SDN 243 CICABE KOTA BANDUNG',0,17,0,0,17);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Arcamanik','SDN 244 GURUMINDA KOTA BANDUNG',6,0,0,0,6);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Babakan Ciparay','SDN 245 SUMBERSARI INDAH KOTA BANDUNG',6,6,0,0,12);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Buahbatu','SDN 246 MARGACINTA KOTA BANDUNG',6,2,0,0,8);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Cibiru','SDN 247 SUKAPURA KOTA BANDUNG',0,12,0,0,12);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Antapani','SDN 248 SINDANGSARI KOTA BANDUNG',1,3,0,0,4);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Astanaanyar','SDN 249 ASTANAANYAR KOTA BANDUNG',7,1,0,0,8);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Bandung Kidul','SDN 250 JAKAPURWA KOTA BANDUNG',0,15,0,0,15);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Bojong Loa Kaler','SDN 251 JAMIKA KOTA BANDUNG',0,10,0,0,10);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Sukasari','SDN 252 SETIABUDI KOTA BANDUNG',18,0,0,0,18);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Ujungberung','SDN 253 PANGGUNGSARI KOTA BANDUNG',0,7,0,0,7);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Antapani','SDN 254 GRIYA BUMI ANTAPANI KOTA BANDUNG',0,6,1,0,7);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Antapani','SDN 255 GRIYA BUMI ANTAPANI KOTA BANDUNG',0,8,2,0,10);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Bandung Kulon','SDN 256 CIGONDEWAH HILIR KOTA BANDUNG',5,0,0,1,6);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Lengkong','SDN 257 PELITA KOTA BANDUNG',4,15,0,0,19);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Panyileukan','SDN 258 SUKARELA KOTA BANDUNG',0,10,1,0,11);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Antapani','SDN 259 GRIYA BUMI ANTAPANI KOTA BANDUNG',0,5,4,8,17);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Antapani','SDN 260 GRIYA BUMI ANTAPANI KOTA BANDUNG',0,7,0,0,7);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Buahbatu','SDN 261 MARGAHAYU RAYA KOTA BANDUNG',19,0,0,0,19);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Panyileukan','SDN 262 PANYILEUKAN KOTA BANDUNG',0,9,1,0,10);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Rancasari','SDN 263 RANCALOA KOTA BANDUNG',0,17,0,0,17);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Antapani','SDN 264 GRIYA BUMI ANTAPANI KOTA BANDUNG',0,6,0,0,6);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Astanaanyar','SDN 265 BANDUNGKULON KOTA BANDUNG',5,10,0,0,15);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Bandung Kidul','SDN 266 MENGGER KOTA BANDUNG',0,0,6,0,6);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Antapani','SDN 267 GRIYA BUMI ANTAPANI KOTA BANDUNG',0,7,0,0,7);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Panyileukan','SDN 268 PANYILEUKAN KOTA BANDUNG',0,7,0,3,10);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Antapani','SDN 269 GRIYA BUMI ANTAPANI KOTA BANDUNG',1,5,0,0,6);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Bojong Loa Kaler','SDN 270 GENTRA MASEKDAS KOTA BANDUNG',0,10,0,0,10);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Panyileukan','SDN 271 PANGHEGAR KOTA BANDUNG',0,9,0,0,9);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Sukajadi','SDN 272 SUKASARI KOTA BANDUNG',2,8,0,0,10);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Bandung Kulon','SDN 273 GEMPOL SARI KOTA BANDUNG',0,8,0,0,8);
INSERT INTO kondisiruangan(Nama_Kecamatan,Nama_Sekolah,Baik,Rusak_Ringan,Rusak_Sedang,Rusak_Berat,Jumlah_Ruangan) VALUES ('Gedebage','SDN 274 CEMPAKA ARUM KOTA BANDUNG',1,14,0,0,15);
